spring:
  application:
    name: task-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/task_api}
    username: ${DB_USERNAME:task_api}
    password: ${DB_PASSWORD:task_api}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
